name: news.json update

on:
  schedule:
    # Run every 3 hours
    - cron: 0 */3 * * *

jobs:
  # This workflow has only one job.
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        key: ${{ secrets.data_daily_update }}
        ssh-key: ${{ secrets.data_daily_update }}
        ref: github-action
        path: stop-covid19-sfbayarea

    # Checkout news scraper repo
    - name: Checkout Data Scraper
      uses: actions/checkout@v2
      with:
        key: ${{ secrets.data_daily_update }}
        ssh-key: ${{ secrets.data_daily_update }}
        repository: sfbrigade/data-covid19-sfbayarea
        path: data-covid19-sfbayarea

    # The scraper uses Python 3.7+, so make sure we've got the latest 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    # Install dependencis
    # - The commit that was checked out will be available as $SCRAPER_COMMIT.
    - name: Install Data Scraper & Dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/data-covid19-sfbayarea
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

        # Keep track of the version used so we can use it in commit messages
        echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"

    # Run the news scraper
    - name: Scrape News
      run: |
        python scraper_news.py --format json_simple > "${GITHUB_WORKSPACE}/stop-covid19-sfbayarea/data/news.json"
    
    # Check if we have news update, then commit
    - name: Commit Changes
      run: |
        cd ${GITHUB_WORKSPACE}/stop-covid19-sfbayarea
        if [[ "$(git status --porcelain)" =~ 'data/' ]]; then
          # Configure git
          git config user.name ${{ secrets.githubaction_config_user_name }}
          git config user.email ${{ secrets.githubaction_config_user_email }}

          echo 'Committing updated news data...'
          git add data/
          git commit -m "GitHubAction: news data update.

          Created with commit ${SCRAPER_COMMIT} from sfbrigade/data-covid19-sfbayarea
          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${SCRAPER_COMMIT}
          "
          git push
          echo "Committed: $(git show HEAD --no-patch --format=reference)"
          echo 'You should make a pull request to put these changes on master!'
        else
          echo 'Nothing to commit!'
        fi
