name: news.json update

on:
  schedule:
    # Run every 3 hours
    - cron: 0 */3 * * *

jobs:
  # This workflow has only one job.
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        key: ${{ secrets.data_daily_update }}
        ssh-key: ${{ secrets.data_daily_update }}
        ref: github-action

    # The scraper uses Python 3.7+, so make sure we've got the latest 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    
    # Check out the data scraper *alongside* this repo, not inside it. This way
    # nothing that happens here interferes with the main repo.
    # - The path to the data scraper will be available as $SCRAPER_PATH.
    # - The commit that was checked out will be available as $SCRAPER_COMMIT.
    - name: Install Data Scraper & Dependencies
      run: |
        cd ..
        git clone https://github.com/sfbrigade/data-covid19-sfbayarea.git
        cd data-covid19-sfbayarea
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

        # Keep track of where we checked out the scraper codebase
        echo "::set-env name=SCRAPER_PATH::$(pwd)"
        
        # Keep track of the version used so we can use it in commit messages
        echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"

    - name: Scrape News
      run: |
        cd $SCRAPER_PATH
        python scraper_news.py --format json_simple > "${GITHUB_WORKSPACE}/data/news.json"
    
    - name: Commit Changes
      run: |
        if [[ "$(git status --porcelain)" =~ 'data/' ]]; then
          # Configure git
          git config user.name ${{ secrets.githubaction_config_user_name }}
          git config user.email ${{ secrets.githubaction_config_user_email }}

          echo 'Committing updated news data...'
          git add data/
          git commit -m "GitHubAction: news data update.

          Created with commit ${SCRAPER_COMMIT} from sfbrigade/data-covid19-sfbayarea
          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${SCRAPER_COMMIT}
          "
          git push
          echo "Committed: $(git show HEAD --no-patch --format=reference)"
          echo 'You should make a pull request to put these changes on master!'
        else
          echo 'Nothing to commit!'
        fi
